Added run as user flag (-U) to 'apk-build' and 'build' commands.

diff --git a/build/scripts/gitobld-apk-build b/build/scripts/gitobld-apk-build
--- a/build/scripts/gitobld-apk-build
+++ b/build/scripts/gitobld-apk-build
@@ -57,7 +57,7 @@ usage() {
 		    -o  Set output directory
 		    -p  Set path to packager public key
 		    -R  Build APKBUILD depencies
-		    -U  Run container with this user
+		    -U  Set user to run 'abuild' image
 	EOF
 
 	exit 0
@@ -72,7 +72,7 @@ while getopts "bd:hk:o:p:RU:" opt; do
 		o) BUILD_OUTPUT_DIR=$OPTARG ;;
 		p) PKG_PUBKEY_PATH=$OPTARG ;;
 		R) build_deps_opt='-R' ;;
-		U) RUN_AS_USER=$OPTARG ;;
+		U) container_user=$OPTARG ;;
 	esac
 done
 
@@ -92,9 +92,17 @@ PKG_DIRECTORY=${PKG_DIRECTORY:-$PWD/ports}
 PKG_PRIVKEY_PATH=${PKG_PRIVKEY_PATH:-$PWD/keys/packager_key.rsa}
 PKG_PUBKEY_PATH=${PKG_PUBKEY_PATH:-$PKG_PRIVKEY_PATH.pub}
 
-RUN_AS_USER=${RUN_AS_USER:-"$(id -u):$(id -g)"}
-
 GITOBLD_VOLUME=${GITOBLD_VOLUME:-gitobld-volume}
+
+if [ -n "$container_user" ]; then
+	if ! id "$container_user" > /dev/null 2>&1; then
+		die "User not found: $container_user"
+	fi
+
+	RUN_AS_USER="$(id -u $container_user):$(id -g $container_user)"
+else
+	RUN_AS_USER="$(id -u):$(id -g)"
+fi
 
 export RUN_AS_USER
 
diff --git a/build/scripts/gitobld-build b/build/scripts/gitobld-build
--- a/build/scripts/gitobld-build
+++ b/build/scripts/gitobld-build
@@ -51,12 +51,13 @@ usage() {
 		    -p  Set public key url
 		    -P  Set public key path
 		    -u  Set user name for image tags
+		    -U  Set user to run 'abuild' and 'apk-server' images
 	EOF
 
 	exit 0
 }
 
-while getopts "bd:e:hk:KNo:r:RPSu:" opt; do
+while getopts "bd:e:hk:KNo:r:RPSu:U:" opt; do
 	case $opt in
 		b) rebuild_image_opt='-b' ;;
 		d) PKG_DIRECTORY=$OPTARG ;;
@@ -71,6 +72,7 @@ while getopts "bd:e:hk:KNo:r:RPSu:" opt; do
 		p) PKG_PUBKEY_URL=$OPTARG ;;
 		P) PKG_PUBKEY_PATH=$OPTARG ;;
 		u) username_opt='-u '"$OPTARG" ;;
+		U) container_user=$OPTARG ;;
 	esac
 done
 
@@ -95,6 +97,18 @@ if [ -z "$PKG_PUBKEY_URL" -a -n "$RUN_SERVER" ]; then
 fi
 
 GITOBLD_NETWORK=${GITOBLD_NETWORK:-gitobld-network}
+
+if [ -n "$container_user" ]; then
+	if ! id "$container_user" > /dev/null 2>&1; then
+		die "User not found: $container_user"
+	fi
+
+	RUN_AS_USER="$(id -u $container_user):$(id -g $container_user)"
+else
+	RUN_AS_USER="$(id -u):$(id -g)"
+fi
+
+export RUN_AS_USER
 
 if [ -n "$BUILD_APKS" ]; then
 	BUILD_DEPS=1 gitobld-apk-build $@
