Refactor tools to work with the base image.

diff --git a/build/scripts/gitobld-build b/build/scripts/gitobld-build
--- a/build/scripts/gitobld-build
+++ b/build/scripts/gitobld-build
@@ -6,49 +6,59 @@ if [ -f "$GITOBLD_COMMON" ]; then
 	. "$GITOBLD_COMMON"
 fi
 
-build_tool_image() {
-	tool_name=$1
-	tool_tag=$(gitobld-packages -T $username_opt $tool_name)
+build_image() {
+	image_id="$1"
 
-	if [ -z "$tool_tag" ]; then
-		error "Invalid tool name '$tool_name'"
-		return 1
+	if [ "$image_id" = base ]; then
+		[ -n "$PKG_REPOSITORY" ] && build_args="$build_args --build-arg PKG_REPOSITORY=$PKG_REPOSITORY"
+		[ -n "$PKG_PUBKEY_URL" ] && build_args="$build_args --build-arg PKG_PUBKEY_URL=$PKG_PUBKEY_URL"
+
+		image_tag="$base_image_tag"
+		build_context='base/'
+	else
+		image_tag=$(gitobld-packages -T $username_opt $image_id)
+
+		if [ -z "$image_tag" ]; then
+			error "Invalid tool name '$image_id'"
+			return 1
+		fi
+
+		if ! gitobld-packages -de $image_id; then
+			error "No tool with '$image_id' name at library directory."
+			return 1
+		fi
+
+		build_context='library/'"$image_id"
 	fi
 
-	if ! gitobld-packages -de $tool_name; then
-		error "No tool with '$tool_name' name at library directory."
-		return 1
-	fi
+	build_args="$build_args --network $GITOBLD_NETWORK"
 
 	[ -n "$BUILD_NO_CACHE" ] && build_args="$build_args --no-cache"
-	
-	[ -n "$GITOBLD_NETWORK" ] && build_args="$build_args --network $GITOBLD_NETWORK"
 
-	[ -n "$PKG_REPOSITORY" ] && build_args="$build_args --build-arg PKG_REPOSITORY=$PKG_REPOSITORY"
-	[ -n "$PKG_PUBKEY_URL" ] && build_args="$build_args --build-arg PKG_PUBKEY_URL=$PKG_PUBKEY_URL"
+	msg "Building Docker image for '$image_id'..."
+	gitobld-docker -bf "$image_tag" "$build_context" $build_args
 
-	msg "Building Docker image for '$tool'..."
-	gitobld-docker -b $tool_tag library/"$tool_name" $build_args
+	unset build_args
 }
 
 usage() {
 	cat <<-EOF
-		Usage: $program [OPTION]... all | TOOL...
+		Usage: $program [OPTION]... all | base | TOOL...
 
-		Update dockerfiles using a template
+		Build GITO images
 
 		Options:
 		    -b  Rebuild 'apk-server' image, when using '-S' flag
-		    -d
+		    -d  Set directory with Alpine ports.
 		    -e  Set apk repository for tools
 		    -h  Show this help
 		    -k  Set private key path
 		    -N  Do not use cache when building the image
 		    -o  Set output directory, when using '-R' flag
-		    -r  Set package repository path
-		    -R  Build Alpine packages for tools
+		    -r  Build Alpine packages for tools
+		    -R  Set package repository path, when building base image
 		    -S  Run local server for apks
-		    -p  Set public key url
+		    -p  Set public key url, when building base image
 		    -P  Set public key path
 		    -u  Set user name for image tags
 		    -U  Set user to run 'abuild' and 'apk-server' images
@@ -57,7 +67,7 @@ usage() {
 	exit 0
 }
 
-while getopts "bd:e:hk:KNo:r:RPSu:U:" opt; do
+while getopts "bd:e:hk:KNo:rR:PSu:U:" opt; do
 	case $opt in
 		b) rebuild_image_opt='-b' ;;
 		d) PKG_DIRECTORY=$OPTARG ;;
@@ -66,13 +76,13 @@ while getopts "bd:e:hk:KNo:r:RPSu:U:" opt; do
 		k) PKG_PRIVKEY_PATH=$OPTARG ;;
 		N) BUILD_NO_CACHE=1 ;;
 		o) BUILD_OUTPUT_DIR=$OPTARG ;;
-		r) REPOSITORY_PATH=$OPTARG ;;
-		R) BUILD_APKS=1 ;;
+		r) BUILD_APKS=1 ;;
+		R) repository_path="$OPTARG" ;;
 		S) RUN_SERVER=1 ;;
 		p) PKG_PUBKEY_URL=$OPTARG ;;
 		P) PKG_PUBKEY_PATH=$OPTARG ;;
 		u) username_opt='-u '"$OPTARG" ;;
-		U) container_user=$OPTARG ;;
+		U) container_user_opt='-U '"$OPTARG" ;;
 	esac
 done
 
@@ -82,48 +92,30 @@ if [ "$#" -eq 0 ]; then
 	die "No tools passed to '$program' command."
 fi
 
-[ "$1" = all ] && set -- $(gitobld-packages -L)
+[ "$1" = all ] && set -- base $(gitobld-packages -L)
 
-APK_SERVER_HOST=${APK_SERVER_HOST:-gitobld-apk-server.local}
-
-PKG_DIRECTORY=${PKG_DIRECTORY:-$PWD/ports}
-PKG_REPOSITORY=${PKG_REPOSITORY:-http://"$APK_SERVER_HOST"/packages/aports}
-
-PKG_PRIVKEY_PATH=${PKG_PRIVKEY_PATH:-$PWD/keys/packager_key.rsa}
-PKG_PUBKEY_PATH=${PKG_PUBKEY_PATH:-$PWD/keys/packager_key.rsa.pub}
+base_image_tag=${BASE_IMAGE_TAG:-gitobioinformatics/gito:3.8}
 
 if [ -z "$PKG_PUBKEY_URL" -a -n "$RUN_SERVER" ]; then
 	PKG_PUBKEY_URL='http://'"$APK_SERVER_HOST"'/'"${PKG_PUBKEY_PATH##*/}"
 fi
 
-GITOBLD_NETWORK=${GITOBLD_NETWORK:-gitobld-network}
-
-if [ -n "$container_user" ]; then
-	if ! id "$container_user" > /dev/null 2>&1; then
-		die "User not found: $container_user"
-	fi
-
-	RUN_AS_USER="$(id -u $container_user):$(id -g $container_user)"
-else
-	RUN_AS_USER="$(id -u):$(id -g)"
+if [ -n "$BUILD_OUTPUT_DIR" -a -z "$repository_path" ]; then
+	repository_path=$BUILD_OUTPUT_DIR
 fi
 
-export RUN_AS_USER
+packages=$(echo "$@" | sed -e 's/base//')
 
-if [ -n "$BUILD_APKS" ]; then
-	BUILD_DEPS=1 gitobld-apk-build $@
-fi
-
-if [ -n "$BUILD_OUTPUT_DIR" -a -z "$REPOSITORY_PATH" ]; then
-	REPOSITORY_PATH=$BUILD_OUTPUT_DIR
+if [ -n "$BUILD_APKS" ] && [ -n "$packages" ]; then
+	gitobld-apk-build -r $container_user_opt $packages
 fi
 
 if [ -n "$RUN_SERVER" ]; then
 	gitobld-apk-server $rebuild_image_opt
 fi
 
-for tool in $@; do
-	build_tool_image "$tool"
+for image in $@; do
+	build_image "$image"
 done
 
 [ -n "$RUN_SERVER" ] && gitobld-apk-server -d
diff --git a/build/scripts/gitobld-push b/build/scripts/gitobld-push
--- a/build/scripts/gitobld-push
+++ b/build/scripts/gitobld-push
@@ -6,39 +6,43 @@ if [ -f "$GITOBLD_COMMON" ]; then
 	. "$GITOBLD_COMMON"
 fi
 
-push_tool_image() {
-	tool_name=$1
-	tool_tag=$(gitobld-packages -T $username_opt $1)
+push_image() {
+	image_id="$1"
 
-	if [ -z "$tool_tag" ]; then
-		error "Invalid tool name '$tool_name'"
+	if [ "$image_id" = base ]; then
+		image_tag="$BASE_IMAGE_TAG"
+	else
+		image_tag=$(gitobld-packages -T $username_opt "$image_id")
+
+		if [ -z "$image_tag" ]; then
+			error "Invalid tool name '$image_id'"
+			return 1
+		fi
+	fi
+
+	if ! gitobld-docker -qet image "$image_tag"; then
+		error "Image '$image_id' don't exists."
 		return 1
 	fi
 
-	if ! gitobld-docker -qet image $tool_tag; then
-		error "Image for '$tool_name' don't exists."
-		return 1
-	fi
-
-	[ -z "$ONLY_SEND_LATEST" ] && tags="$tool_tag"
+	[ -z "$ONLY_SEND_LATEST" ] && tags="$image_tag"
 
 	if [ -n "$SEND_LATEST" -o -n "$ONLY_SEND_LATEST" ]; then
-		tags="$tags ${tool_tag%:*}:latest"
+		tags="$tags ${image_tag%:*}:latest"
 	fi
 
 	if [ -n "$REMOTE_REPOSITORY" ]; then
 		tags=$(echo $tags | sed -e 's,[^ ]* *,'"$REMOTE_REPOSITORY"'/&,g')
 	fi
 
-	msg "Pushing '$tool' to '${REMOTE_REPOSITORY:-docker.io}'..."
-
-	gitobld-docker -T "$tool_tag" $tags
+	msg "Pushing '$image_id' to '${REMOTE_REPOSITORY:-docker.io}'..."
+	gitobld-docker -T "$image_tag" $tags
 	gitobld-docker -p $tags
 }
 
 usage() {
 	cat <<-EOF
-		Usage: $program [OPTION]... all | TOOL...
+		Usage: $program [OPTION]... all | base | TOOL...
 
 		Send images to remote repository
 
@@ -69,11 +73,11 @@ if [ "$#" -eq 0 ]; then
 	die "No tools passed to '$program' command."
 fi
 
-[ "$1" = all ] && set -- $(gitobld-packages -L)
+[ "$1" = all ] && set -- base $(gitobld-packages -L)
 
 REPOSITORY_USER=${REPOSITORY_USER:-gitobioinformatics}
 
-for tool in $@; do
-	push_tool_image $tool
+for image in $@; do
+	push_image "$image"
 done
 
