The 'gitobld' command is working again.     - Added new features to 'updatedf', save changes made on tool files,     added a badge to readme, add better titles to readmes.

diff --git a/build/scripts/gitobld-build b/build/scripts/gitobld-build
--- a/build/scripts/gitobld-build
+++ b/build/scripts/gitobld-build
@@ -1,41 +1,125 @@
 #!/bin/sh
 
+set -e
+
+. ${GITOBLD_COMMON:-true}
+
 build_tool_image() {
-	_tool_name=$1
-	_tool_tag=$(gitobld-library -t $_tool_name)
+	tool_name=$1
+	tool_tag=$(gitobld-library -t $tool_name)
 
-	if [ -z "$_tool_tag" ]; then
-		#error "Invalid tool name '$_tool_name'"
-		echo "Invalid tool name '$_tool_name'"
+	if [ -z "$tool_tag" ]; then
+		error "Invalid tool name '$tool_name'"
 		return 1
 	fi
 
-	if ! gitobld-library -e $_tool_name; then
-		#error "No tool with '$_tool_name' name at library directory."
-		echo "No tool with '$_tool_name' name at library directory."
+	if ! gitobld-library -e $tool_name; then
+		error "No tool with '$tool_name' name at library directory."
 		return 1
 	fi
 
-	_build_args="--tag $_tool_tag"
+	build_args="--tag $tool_tag"
 
-	[ -n "$BUILD_NO_CACHE" ] && _build_args="$_build_args --no-cache"
+	[ -n "$BUILD_NO_CACHE" ] && build_args="$build_args --no-cache"
 	
-	[ -n "$GITOBLD_NETWORK" ] && _build_args="$_build_args --network $GITOBLD_NETWORK"
+	[ -n "$GITOBLD_NETWORK" ] && build_args="$build_args --network $GITOBLD_NETWORK"
 
-	[ -n "$PKG_REPOSITORY" ] && _build_args="$_build_args --build-arg PKG_REPOSITORY=$PKG_REPOSITORY"
-	[ -n "$PKG_PUBKEY_URL" ] && _build_args="$_build_args --build-arg PKG_PUBKEY_URL=$PKG_PUBKEY_URL"
+	[ -n "$PKG_REPOSITORY" ] && build_args="$build_args --build-arg PKG_REPOSITORY=$PKG_REPOSITORY"
+	[ -n "$PKG_PUBKEY_URL" ] && build_args="$build_args --build-arg PKG_PUBKEY_URL=$PKG_PUBKEY_URL"
 
-	docker build $_build_args library/"$_tool_name"
+	msg "Building Docker image for '$tool'..."
+
+	docker build $build_args library/"$tool_name"
 }
 
-APK_SERVER_HOST=${APK_SERVER_HOST:-gitobld_apk_server.local}
+usage() {
+	cat <<-EOF
+		Usage: $program [OPTION]... all | TOOL...
 
+		Update dockerfiles using a template
+
+		Options:
+		    -b  Rebuild 'apk-server' image, when using '-S' flag
+		    -B  Rebuild 'gito' base image.
+		    -c  Recreate containers
+		    -d
+		    -e  Set apk repository for tools
+		    -h  Show this help
+		    -k  Set private key path
+		    -N  Do not use cache when building the image
+		    -o  Set output directory, when using '-R' flag
+		    -r  Set package repository path
+		    -R  Build Alpine packages for tools
+		    -S  Run local server for apks
+		    -p  Set public key url
+		    -P  Set public key path
+		    -u  Set user name for image tags
+	EOF
+
+	exit 0
+}
+
+while getopts "bBcd:e:hk:KNo:r:RPSu:" opt; do
+	case $opt in
+		b) BUILD_IMAGES=1 ;;
+		B) BUILD_BASE_IMAGE=1 ;;
+		c) FORCE_RECREATE=1 ;;
+		d) PKG_DIRECTORY=$OPTARG ;;
+		e) PKG_REPOSITORY=$OPTARG ;;
+		h) usage ;;
+		k) PKG_PRIVKEY_PATH=$OPTARG ;;
+		N) BUILD_NO_CACHE=1 ;;
+		o) BUILD_OUTPUT_DIR=$OPTARG ;;
+		r) REPOSITORY_PATH=$OPTARG ;;
+		R) BUILD_APKS=1 ;;
+		S) RUN_SERVER=1 ;;
+		p) PKG_PUBKEY_URL=$OPTARG ;;
+		P) PKG_PUBKEY_PATH=$OPTARG ;;
+		u) REPOSITORY_USER=$OPTARG ;;
+	esac
+done
+
+shift $((OPTIND-1))
+
+if [ "$#" -eq 0 ]; then
+	die "No tools passed to '$program' command."
+fi
+
+[ "$1" = all ] && set -- $(gitobld-library -a)
+
+APK_SERVER_HOST=${APK_SERVER_HOST:-gitobld-apk-server.local}
+
+BASE_IMAGE_TAG=${BASE_IMAGE_TAG:-gitobioinformatics/gito}
+
+PKG_DIRECTORY=${PKG_DIRECTORY:-$PWD/ports}
 PKG_REPOSITORY=${PKG_REPOSITORY:-http://"$APK_SERVER_HOST"/packages/aports}
 
+PKG_PRIVKEY_PATH=${PKG_PRIVKEY_PATH:-$PWD/keys/packager_key.rsa}
 PKG_PUBKEY_PATH=${PKG_PUBKEY_PATH:-$PWD/keys/packager_key.rsa.pub}
-PKG_PUBKEY_URL='http://'"$APK_SERVER_HOST"'/'"${PKG_PUBKEY_PATH##*/}"
+
+if [ -z "$PKG_PUBKEY_URL" -a -n "$RUN_SERVER" ]; then
+	PKG_PUBKEY_URL='http://'"$APK_SERVER_HOST"'/'"${PKG_PUBKEY_PATH##*/}"
+fi
+
+REPOSITORY_USER=${REPOSITORY_USER:-gitobioinformatics}
 
 GITOBLD_NETWORK=${GITOBLD_NETWORK:-gitobld-network}
 
-build_tool_image "$1"
+[ -n "$BUILD_BASE_IMAGE" ] && build_base_image
+
+if [ -n "$BUILD_APKS" ]; then
+	BUILD_DEPS=1 gitobld-apk-build $@
+fi
+
+if [ -n "$BUILD_OUTPUT_DIR" -a -z "$REPOSITORY_PATH" ]; then
+	REPOSITORY_PATH=$BUILD_OUTPUT_DIR
+fi
+
+[ -n "$RUN_SERVER" ] && gitobld-apk-server
+
+for tool in $@; do
+	build_tool_image "$tool"
+done
+
+[ -n "$RUN_SERVER" ] && gitobld-apk-server -s
 
diff --git a/build/scripts/gitobld-push b/build/scripts/gitobld-push
--- a/build/scripts/gitobld-push
+++ b/build/scripts/gitobld-push
@@ -1,38 +1,83 @@
 #!/bin/sh
 
+set -e
+
+. ${GITOBLD_COMMON:-true}
+
 push_tool_image() {
-	_tool_name=$1
-	_tool_tag=$(get_tool_tag $1)
+	tool_name=$1
+	tool_tag=$(gitobld-library -t $1)
 
-	if [ -z "$_tool_tag" ]; then
-		#error "Invalid tool name '$_tool_name'"
-		echo "Invalid tool name '$_tool_name'"
+	if [ -z "$tool_tag" ]; then
+		error "Invalid tool name '$tool_name'"
 		return 1
 	fi
 
-	if ! docker_obj_exists image $_tool_tag; then
-		#error "Image for '$_tool_name' don't exists."
-		echo "Image for '$_tool_name' don't exists."
+	if ! gitobld-docker -qe image $tool_tag; then
+		error "Image for '$tool_name' don't exists."
 		return 1
 	fi
 
-	[ -z "$ONLY_SEND_LATEST" ] && _send_tags="$_tool_tag"
+	[ -z "$ONLY_SEND_LATEST" ] && tags="$tool_tag"
 
 	if [ -n "$SEND_LATEST" -o -n "$ONLY_SEND_LATEST" ]; then
-		_send_tags="$_send_tags ${_tool_tag%:*}:latest"
+		tags="$tags ${tool_tag%:*}:latest"
 	fi
 
 	if [ -n "$REMOTE_REPOSITORY" ]; then
-		_send_tags=$(echo $_send_tags | sed -e 's,[^ ]* *,'"$REMOTE_REPOSITORY"'/&,g')
+		tags=$(echo $tags | sed -e 's,[^ ]* *,'"$REMOTE_REPOSITORY"'/&,g')
 	fi
 
-	for tag in $_send_tags; do
-		if [ "$tag" != "$_tool_tag" ]; then
-			docker tag $_tool_tag $tag
+	msg "Pushing '$tool' to '${REMOTE_REPOSITORY:-docker.io}'..."
+
+	for tag in $tags; do
+		if [ "$tag" != "$tool_tag" ]; then
+			docker tag $tool_tag $tag
 		fi
 
 		echo "Pushing '$tag'..."
 		docker push $tag
 	done
 }
+
+usage() {
+	cat <<-EOF
+		Usage: $program [OPTION]... all | TOOL...
+
+		Send images to remote repository
+
+		Options:
+		    -h  Show this help
+		    -l  Tag current version as 'latest', and push both tags to remote
+		    -L  Tag current version as 'latest', and only push this tag
+		    -r  Set remote repository
+		    -u  Set user for images tags
+	EOF
+
+	exit 0
+}
+
+while getopts "hlLr:u:" opt; do
+	case $opt in
+		h) usage ;;
+		l) SEND_LATEST=1 ;;
+		L) ONLY_SEND_LATEST=1 ;;
+		r) REMOTE_REPOSITORY=$OPTARG ;;
+		u) REPOSITORY_USER=$OPTARG ;;
+	esac
+done
+
+shift $((OPTIND-1))
+
+if [ "$#" -eq 0 ]; then
+	die "No tools passed to '$program' command."
+fi
+
+[ "$1" = all ] && set -- $(gitobld-library -a)
+
+REPOSITORY_USER=${REPOSITORY_USER:-gitobioinformatics}
+
+for tool in $@; do
+	push_tool_image $tool
+done
 
diff --git a/build/scripts/gitobld-updatedf b/build/scripts/gitobld-updatedf
--- a/build/scripts/gitobld-updatedf
+++ b/build/scripts/gitobld-updatedf
@@ -1,54 +1,112 @@
 #!/bin/sh
 
+set -e
+
+. ${GITOBLD_COMMON:-true}
+
+apply_patch() {
+	target="$1"
+
+	if [ -f "$target" ]; then
+		tee "$target".new | diff - $target | patch "$target".new
+
+		rm "$target"
+		mv "$target".new $target
+	else
+		cat > $target
+	fi
+}
+
 update_tool_df() {
 	[ -z "$1" ] && return 1
 
-	_tool_name=$1
+	tool_id=$1
 
-	if ! gitobld-ports -e $_tool_name; then
-		#error "Missing package for '$_tool_name' at ports directory."
-		echo "Missing package for '$_tool_name' at ports directory."
+	if ! gitobld-ports -e $tool_id; then
+		error "Missing package for '$tool_id' at ports directory."
 		return 1
 	fi
 
-	_tool_dir=library/$_tool_name
+	tool_dir=library/$tool_id
 
-	mkdir -p $_tool_dir
+	tool_name=$(gitobld-library -n $tool_id)
+	tool_version=$(gitobld-library -v $tool_id)
+	tool_homepage=$(gitobld-library -w $tool_id)
+
+	tool_name=${tool_name:-$tool_id}
+	tool_version=${tool_version:-$(gitobld-ports -v $tool_id)}
+	tool_homepage=${tool_homepage:-$(gitobld-ports -u $tool_id)}
+
+	msg "Updating '$tool'..."
+
+	mkdir -p $tool_dir
 	sed \
-		-e 's/%%TOOL_NAME%%/'"$_tool_name"'/g' \
+		-e 's/%%TOOL_ID%%/'"$tool_id"'/g' \
+		-e 's/%%TOOL_NAME%%/'"$tool_name"'/g' \
 		-e 's/%%ALPINE_VERSION%%/'"$ALPINE_VERSION"'/g' \
+		-e 's/%%TOOL_VERSION%%/'"$tool_version"'/g' \
+		-e 's,%%TOOL_HOMEPAGE%%,'"$tool_homepage"',g' \
 		-e 's,%%PKG_PUBKEY_URL%%,'"$PKG_PUBKEY_URL"',g' \
 		-e 's,%%PKG_PUBKEY%%,'"$PKG_PUBKEY"',g' \
 		-e 's,%%PKG_REPOSITORY%%,'"$PKG_REPOSITORY"',g' \
 		build/template/Dockerfile.template \
-		> $_tool_dir/Dockerfile
+		| apply_patch $tool_dir/Dockerfile
 
 	echo "Added Dockerfile"
 
-	if [ ! -f "$_tool_dir"/docker-entrypoint.sh ]; then
-		cp build/template/docker-entrypoint.sh "$_tool_dir"
-		echo "Added docker-entrypoint.sh"
-	fi
+	cat build/template/docker-entrypoint.sh | apply_patch "$tool_dir"/docker-entrypoint.sh
+	echo "Added docker-entrypoint.sh"
 
-	if [ ! -f "$_tool_dir"/README.md ]; then
-		sed \
-			-e 's/%%TOOL_NAME%%/'"$_tool_name"'/g' \
-			-e 's/%%TOOL_BADGES%%//g' \
-			-e 's/%%TOOL_DESCRIPTION%%/'"$(gitobld-ports -d $_tool_name)"'/g' \
-			build/template/README.md \
-			> $_tool_dir/README.md
-		echo "Added README.md"
-	fi
+	badges="[![Version](https://img.shields.io/badge/Version-$tool_version-blue.svg)]()"
+
+	sed \
+		-e 's/%%TOOL_ID%%/'"$tool_id"'/g' \
+		-e 's/%%TOOL_NAME%%/'"$tool_name"'/g' \
+		-e 's/"%%TOOL_VERSION%%/'"$tool_version"'/g' \
+		-e 's,%%TOOL_HOMEPAGE%%,'"$tool_homepage"',g' \
+		-e 's,%%TOOL_BADGES%%,'"$badges"',g' \
+		-e 's/%%TOOL_DESCRIPTION%%/'"$(gitobld-library -d $tool_id)"'/g' \
+		build/template/README.md \
+		| apply_patch $tool_dir/README.md
+	echo "Added README.md"
 }
 
-while getopts "a:" opt; do
+usage() {
+	cat <<-EOF
+		Usage: $program [OPTION]... all | TOOL...
+
+		Update dockerfiles using a template
+
+		Options:
+		    -a  Set alpine version for dockerfiles
+		    -h  Show this help
+		    -k  Set public key url for apks
+		    -r  Set apk repository for tools
+	EOF
+
+	exit 0
+}
+
+ALPINE_VERSION=3.8
+
+while getopts "hk:r:" opt; do
 	case $opt in
 		a) ALPINE_VERSION=$OPTARG ;;
-		h) exit 0 ;;
+		h) usage ;;
+		k) PKG_PUBKEY_URL=$OPTARG ;;
+		r) PKG_REPOSITORY=$OPTARG ;;
 	esac
 done
 
 shift $((OPTIND-1))
 
-update_tool_df "$1"
+if [ "$#" -eq 0 ]; then
+	die "No tools passed to '$program' command."
+fi
+
+[ "$1" = all ] && set -- $(gitobld-library -a)
+
+for tool in $@; do
+	update_tool_df "$tool"
+done
 
